<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SoalSeederOptimized extends Seeder
{
    public function run()
    {
        $data = [
            // Soal untuk kaidah 1 (Isim Mufrad dan Jamak) - 10 soal terpilih
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'Apa bentuk jamak dari كِتَابٌ (kitabun)?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2, // guru1
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'Manakah yang termasuk isim mufrad?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2, // guru1
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'مُدَرِّسُونَ (mudarrisuna) adalah bentuk jamak dari kata?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2, // guru1
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'Manakah yang termasuk isim jamak taksir?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'مُسْلِمُونَ (muslimuna) artinya adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'Isim mufrad menunjukkan jumlah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'تِلْمِيذٌ (tilmidzun) adalah bentuk...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'مَسَاجِدُ (masajidu) adalah jamak dari...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'Isim yang menunjukkan satu benda disebut...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 1,
                'pertanyaan'      => 'جِبَالٌ (jibalun) adalah bentuk jamak dari...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 2 (Isim Mudzakkar dan Muannats) - 10 soal terpilih
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'Apa lawan dari وَلَدٌ (waladun)?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2, // guru1
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'مُسْلِمَةٌ (muslimatun) termasuk jenis isim apa?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2, // guru1
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'إِمْرَأَةٌ (imra\'atun) termasuk jenis isim...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'Tanda isim muannats adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'شَمْسٌ (syamsun) adalah jenis isim...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'Isim yang menunjukkan jenis kelamin perempuan disebut...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'هِنْدٌ (hindun) termasuk isim...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'قَمَرٌ (qamarun) adalah isim...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'Tanda ta\' marbuthah (ة) menunjukkan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 2,
                'pertanyaan'      => 'سَمَاءٌ (sama-un) adalah isim...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 3 (Rafa', Nashab, dan Khafdh) - 10 soal terpilih
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Kata الْوَلَدُُ (al-waladu) berada dalam keadaan apa?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3, // guru2
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Tanda baris untuk keadaan nashab adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3, // guru2
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Tanda khafdh adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Kata yang mendapat kasroh disebut...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Dalam kalimat "رَأَيْتُ الْقَلَمَ", kata الْقَلَمَ berada dalam keadaan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Huruf jar adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Manakah yang bukan termasuk keadaan nahwu?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Isim yang diiringi huruf jar akan berada dalam keadaan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Dalam kalimat "مَرَرْتُ بِالْوَلَدِ", kata الْوَلَدِ...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 3,
                'pertanyaan'      => 'Jumlah keadaan nahwu adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 4 (Al-Marfu\'at) - 10 soal terpilih
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Yang termasuk kata yang selalu rafa\' adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3, // guru2
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Mubtada\' adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Khabar adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Manakah yang selalu rafa\'?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Dalam kalimat "الْوَلَدُ نَاجِحٌ", khabarnya adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Naibul fa\'il adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Khabar mubtada\' bisa berupa...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Dalam kalimat "هُوَ قَائِمٌ", mubtada\'nya adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Isim yang menunjuk pelaku dalam fiil madhi...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 4,
                'pertanyaan'      => 'Kata أَنَّ (anna) beserta isimnya dan khabarnya...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 5 (Al-Mansubat) - 10 soal terpilih
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Dalam kalimat "قَرَأْتُ الْكِتَابَ", kata الْكِتَابَ berada dalam keadaan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2, // guru1
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Maf\'ul bihi adalah contoh dari kata yang...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 2, // guru1
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Maf\'ul bihi adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Masdar adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Manakah yang selalu nashab?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Dalam kalimat "قَرَأْتُ الْكِتَابَ", maf\'ul bihi-nya adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Hal adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Tamyiz adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Mustathnay adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 5,
                'pertanyaan'      => 'Isim yang menjadi objek tindakan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 6 (Al-Majrurat) - 10 soal terpilih
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'Jar wa majrur adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'مِنْ (min) adalah contoh huruf...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'Dalam kalimat "ذَهَبْتُ إِلَى الْمَدْرَسَةِ", kata الْمَدْرَسَةِ...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'Isim yang diiringi huruf jar akan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'عَلَى (\'ala) adalah huruf...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'Manakah yang bukan huruf jar?',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'Kata الْكِتَابِ (al-kitabi) berada dalam keadaan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'إِلَى (ila) menunjukkan arah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'Isim yang menjadi objek preposisi disebut...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 6,
                'pertanyaan'      => 'Jumlah majrur adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 7 (Mubtada\' dan Khabar) - 10 soal terpilih
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Mubtada\' adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Khabar adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Dalam kalimat "الْوَلَدُ نَاجِحٌ", mubtada\'nya adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Khabar mubtada\' harus...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Mubtada\' bisa berupa...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Khabar muqaddam adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Dalam kalimat "فِي الْبَيْتِ رَجُلٌ", mubtada\'nya adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Mubtada\' dan khabar harus...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Syibh mubtada\' adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 7,
                'pertanyaan'      => 'Hubungan antara mubtada\' dan khabar...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 8 (Al-Dhamair) - 10 soal terpilih
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'Dhamir adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'هُوَ (huwa) termasuk dhamir...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'Dhamir muttasil adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'هُمْ (hum) adalah dhamir untuk...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'Dhamir munfasil adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'أَنْتَ (anta) adalah dhamir untuk...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'هِيَ (hiya) adalah dhamir...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'Jenis kelamin dari dhamir أَنْتُ (antu)...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'Dhamir yang terikat dengan fiil...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 8,
                'pertanyaan'      => 'Jumlah dhamir muttasil adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 9 (Isim Isyarah) - 10 soal terpilih
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'Isim isyarah adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'هَذَا (hadza) digunakan untuk menunjuk...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'هَذِهِ (hadzihi) untuk menunjuk...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'ذَلِكَ (dzalika) menunjuk benda...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'تِلْكَ (tilka) adalah isim isyarah untuk...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'هَؤُلَاءِ (ha-ula-i) menunjuk...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'أُولَئِكَ (ula-ika) adalah isim isyarah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'هَنَا (huna) menunjukkan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'هَذَانِ (hadzani) menunjuk...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 9,
                'pertanyaan'      => 'Dalam kalimat "هَذَا الْكِتَابُ", isim isyarahnya adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 2,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],

            // Soal untuk kaidah 10 (Al-Mashdar) - 10 soal terpilih
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Masdar adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'الْقِرَاءَةُ (al-qir-atu) artinya...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Masdar menunjukkan...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Masdar dari fiil قَرَأَ (qara-a) adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Kata الْفَهْمُ (al-fahmu) adalah masdar dari...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Masdal fiil madhi adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Wazan مَفْعَلٌ (maf\'ulun) adalah wazan masdar...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Masdar dari fiil ضَرَبَ (daraba) adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'mudah',
                'poin'           => 10,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Wazan مُفَاعَلَةٌ (mufa-alah) adalah...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sulit',
                'poin'           => 20,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
            [
                'id_materi'       => 10,
                'pertanyaan'      => 'Hubungan antara masdar dan fiil...',
                'tipe_soal'       => 'pilihan_ganda',
                'tingkat_kesulitan'=> 'sedang',
                'poin'           => 15,
                'dibuat_oleh'     => 3,
                'waktu_dibuat'    => date('Y-m-d H:i:s'),
                'waktu_diubah'    => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('soal')->insertBatch($data);
        echo "✅ Generated " . count($data) . " soal optimized untuk LCM research\n";
        echo "📊 Distribution: 10 materi × 10 soal = 100 soal total\n";
        echo "🎯 Difficulty: 40% mudah, 40% sedang, 20% sulit\n";
        echo "🔥 Ready for LCM algorithm testing!\n";
    }
}